{
  "es": {
    "titulo": "La melodía de π",
    "countdownTitle": "⏳ TIEMPO PARA QUE π EMPIECE A SONAR",
    "dias": "DÍAS",
    "horas": "HORAS",
    "min": "MIN",
    "seg": "SEG",
    "live": "LIVE",
    "espera": "ESPERA",
    "desde": "Desde el 14/03/2027",
    "proximos": "Próximos intérpretes",
    "inscripcion": "📝 Inscripción",
    "normas": "📜 Normas",
    "readme": "📖 README",
    "acceso_titulo": "🎤 ¿Ya tienes tu código?",
    "acceso_btn": "Acceder a mi turno",
    "acceso_ayuda": "El código y el segundo de inicio los recibiste por correo al inscribirte.",
    "footer": "Una melodía infinita, tocada por personas finitas, unidas por un mismo pulso, en un mismo ahora.",
    "btn_audio": "🔊 Activar sonido",
    "btn_audio_on": "🔇 Silenciar"
  },
  "en": {
    "titulo": "The Melody of π",
    "countdownTitle": "⏳ TIME UNTIL π BEGINS TO PLAY",
    "dias": "DAYS",
    "horas": "HOURS",
    "min": "MIN",
    "seg": "SEC",
    "live": "LIVE",
    "espera": "WAITING",
    "desde": "From 14/03/2027",
    "proximos": "Next performers",
    "inscripcion": "📝 Sign up",
    "normas": "📜 Rules",
    "readme": "📖 README",
    "acceso_titulo": "🎤 Already have your code?",
    "acceso_btn": "Access my turn",
    "acceso_ayuda": "You received the code and start second by email when you signed up.",
    "footer": "An infinite melody, played by finite people, united by the same pulse, in the same now.",
    "btn_audio": "🔊 Enable sound",
    "btn_audio_on": "🔇 Mute"
  }
}
