{
  "es": {
    "titulo_pagina": "La melodía de π",
    "titulo": "La melodía de π",
    "countdown_titulo": "⏳ TIEMPO PARA QUE π EMPIECE A SONAR",
    "dias": "DÍAS",
    "horas": "HORAS",
    "min": "MIN",
    "seg": "SEG",
    "live": "LIVE",
    "espera": "ESPERA",
    "desde_fecha": "Desde el 14/03/2027",
    "proximos_interprete": "Próximos intérpretes",
    "inscripcion": "📝 Inscripción",
    "normas": "📜 Normas",
    "readme": "📖 README",
    "acceso_titulo": "🎤 ¿Ya tienes tu código?",
    "acceso_btn": "Acceder a mi turno",
    "acceso_ayuda": "El código y el segundo de inicio los recibiste por correo al inscribirte.",
    "codigo_placeholder": "Código (ej. π-ABCD1234)",
    "turno_placeholder": "Segundo de inicio (ej. 1710000000)",
    "footer_texto": "Una melodía infinita, tocada por personas finitas, unidas por un mismo pulso, en un mismo ahora.",
    "btn_audio": "🔊 Activar sonido",
    "btn_audio_on": "🔇 Silenciar",
    "inscripcion_titulo": "📝 Inscripción",
    "nombre": "Nombre completo",
    "email": "Correo electrónico",
    "ubicacion": "País / Ciudad",
    "presentacion": "Presentación (opcional)",
    "acepto": "Acepto las normas de respeto y educación",
    "enviar": "🎶 Enviar inscripción",
    "volver": "← Volver",
    "normas_titulo": "📜 Normas",
    "readme_titulo": "📖 La melodía de π",
    "estado_live": "🔴 LIVE",
    "estado_sonando": "π está sonando ahora",
    "nota_Do": "Do",
    "nota_Re": "Re",
    "nota_Mi": "Mi",
    "nota_Fa": "Fa",
    "nota_Sol": "Sol",
    "nota_La": "La",
    "nota_Si": "Si",
    "nota_Do⁸": "Do⁸",
    "nota_Re⁸": "Re⁸",
    "nota_Mi⁸": "Mi⁸"
  },
  "en": {
    "titulo_pagina": "The Melody of π",
    "titulo": "The Melody of π",
    "countdown_titulo": "⏳ TIME UNTIL π BEGINS TO PLAY",
    "dias": "DAYS",
    "horas": "HOURS",
    "min": "MIN",
    "seg": "SEC",
    "live": "LIVE",
    "espera": "WAITING",
    "desde_fecha": "From 14/03/2027",
    "proximos_interprete": "Next performers",
    "inscripcion": "📝 Sign up",
    "normas": "📜 Rules",
    "readme": "📖 README",
    "acceso_titulo": "🎤 Already have your code?",
    "acceso_btn": "Access my turn",
    "acceso_ayuda": "You received the code and start second by email when you signed up.",
    "codigo_placeholder": "Code (e.g. π-ABCD1234)",
    "turno_placeholder": "Start second (e.g. 1710000000)",
    "footer_texto": "An infinite melody, played by finite people, united by the same pulse, in the same now.",
    "btn_audio": "🔊 Enable sound",
    "btn_audio_on": "🔇 Mute",
    "inscripcion_titulo": "📝 Sign up",
    "nombre": "Full name",
    "email": "Email address",
    "ubicacion": "Country / City",
    "presentacion": "Short bio (optional)",
    "acepto": "I accept the rules of respect and education",
    "enviar": "🎶 Submit registration",
    "volver": "← Back",
    "normas_titulo": "📜 Rules",
    "readme_titulo": "📖 The Melody of π",
    "estado_live": "🔴 LIVE",
    "estado_sonando": "π is playing now",
    "nota_Do": "C",
    "nota_Re": "D",
    "nota_Mi": "E",
    "nota_Fa": "F",
    "nota_Sol": "G",
    "nota_La": "A",
    "nota_Si": "B",
    "nota_Do⁸": "C (8va)",
    "nota_Re⁸": "D (8va)",
    "nota_Mi⁸": "E (8va)"
  }
}
